### PR TITLE
Add debian folder

### PR DESCRIPTION
**Pull request by 3v1n0**
Add support for debian/ubuntu packages building

### CODE REVIEW

**Comment by evilsocket** [comment]
wow that's cool! what's the process for it to be added to the official repos? or were you thinking about some ppa ?

**Comment by 3v1n0** [comment]
Well, I mostly did this in order to build a package for myself, but yes we could get some sponsorship to get this to debian -> ubuntu.

So, for example, we could initiate the [sponsorship request](http://mentors.debian.net/sponsor/rfs-howto), or... Ask @alessio to help with that ;-).

**Comment by 3v1n0** [comment]
Ah, as for a PPA is straight forward... It's just about to create a launchpad user if you don't already have one, create a repo and upload the package source there.

**Comment by evilsocket** [comment]
Honestly, I'm not interested either in having it in some repo or in maintaining it as a package ... I've just developed this for myself, so if someone wants to be its maintainer, that's great, if not ... well ... I'll keep on living anyway :D

**Comment by alessio** [comment]
:+1:
This looks very promising, I'll push it to Debian soon

**Comment by 3v1n0** [comment]
Thanks!

**Comment by alessio** [comment]
FTR opened #3

**Pull request merged**
